#!/usr/bin/env php
<?php

include 'vendor/autoload.php';

use Filip\Console\Application;
use Filip\Console\Kernel;

$namespace = 'Filip\\Console\\Commands\\';

$application = new Application($namespace);

$kernel = new Kernel($application);


$status = $kernel->handle();

exit($status);
echo "hello world";

